# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"!\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"~\n\nBookFilter\x12\x12\n\x05title\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05id_lt\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x12\n\x05id_gt\x18\x04 \x01(\x05H\x03\x88\x01\x01\x42\x08\n\x06_titleB\x05\n\x03_idB\x08\n\x06_id_ltB\x08\n\x06_id_gt\"*\n\rBooksResponse\x12\x19\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\n.book.Book\"\x1e\n\rCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\"*\n\rUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"\x1b\n\rDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xd7\x01\n\x0b\x42ookService\x12\x31\n\x08GetBooks\x12\x10.book.BookFilter\x1a\x13.book.BooksResponse\x12-\n\nCreateBook\x12\x13.book.CreateRequest\x1a\n.book.Book\x12-\n\nUpdateBook\x12\x13.book.UpdateRequest\x1a\n.book.Book\x12\x37\n\nDeleteBook\x12\x13.book.DeleteRequest\x1a\x14.book.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=20
  _globals['_BOOK']._serialized_end=53
  _globals['_BOOKFILTER']._serialized_start=55
  _globals['_BOOKFILTER']._serialized_end=181
  _globals['_BOOKSRESPONSE']._serialized_start=183
  _globals['_BOOKSRESPONSE']._serialized_end=225
  _globals['_CREATEREQUEST']._serialized_start=227
  _globals['_CREATEREQUEST']._serialized_end=257
  _globals['_UPDATEREQUEST']._serialized_start=259
  _globals['_UPDATEREQUEST']._serialized_end=301
  _globals['_DELETEREQUEST']._serialized_start=303
  _globals['_DELETEREQUEST']._serialized_end=330
  _globals['_DELETERESPONSE']._serialized_start=332
  _globals['_DELETERESPONSE']._serialized_end=365
  _globals['_BOOKSERVICE']._serialized_start=368
  _globals['_BOOKSERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
